# utils/config.py
import torch
import logging
from datetime import datetime
import os

class MMTConfig:
    """Project configuration (paths, entity/relation metadata, logging, device selection)."""
    # Base paths
    BASE_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
    # Training paths
    BASE_MODEL_PATH = os.path.join(BASE_PATH, "llm", "llama-2-7b")
    OUTPUT_BASE_PATH = os.path.join(BASE_PATH, "outputs")
    # Data paths
    DATA_PATHS = {
        "embeddings": os.path.join(BASE_PATH, "data", "embeddings"),
        "processed": os.path.join(BASE_PATH, "data", "processed"),
        "raw": os.path.join(BASE_PATH, "data", "raw")
    }

    # File paths
    FILE_PATHS = {
        # Structural embeddings (KGE; used by relation-guided fusion).
        # Note: these files are typically generated by training scripts and may not ship with the repo.
        "kge_entity": f"{DATA_PATHS['embeddings']}/RotatE_entity_64d.npy",
        "kge_relation": f"{DATA_PATHS['embeddings']}/RotatE_relation_64d.npy",

        # Unified multimodal features (relation-guided fusion).
        "visual": f"{DATA_PATHS['embeddings']}/visual.pth",
        "textual": f"{DATA_PATHS['embeddings']}/textual.pth",
        "numeric": f"{DATA_PATHS['embeddings']}/numeric.pth",

        # Processed KG data
        "entity2id": f"{DATA_PATHS['processed']}/entity2id.txt",
        "entityid2name": f"{DATA_PATHS['processed']}/entityid2name.txt",
        "entity2type": f"{DATA_PATHS['processed']}/entity2type.txt",
        "relation2id": f"{DATA_PATHS['processed']}/relation2id.txt",
        "train2id": f"{DATA_PATHS['processed']}/train2id.txt",
        "valid2id": f"{DATA_PATHS['processed']}/valid2id.txt",
        "test2id": f"{DATA_PATHS['processed']}/test2id.txt"
    }

    KGE_TRAINING_NOTE = (
        "Structural embeddings and multimodal retriever checkpoints may not ship with this repo. "
        "Run training/train_kge.py and training/train_multimodal_kge.py before the main experiment."
    )
    # Entity types (by id range)
    ENTITY_TYPES = {
        0: "disease",
        1: "herb",
        2: "molecule",
        3: "target",
    }

    # Relation names
    RELATION_TYPES = {
        0: "CONTAINS",
        1: "HAS_ADME",
        2: "INDICATED_FOR",
        3: "INVOLVED_IN",
        4: "TARGETS",
        5: "TREATS"
    }

    # Entity id ranges
    ENTITY_RANGES = {
        "disease": (0, 866),
        "herb": (867, 1368),
        "molecule": (1369, 15097),
        "target": (15098, 18437)
    }

    # Logging
    @classmethod
    def setup_logging(cls, log_dir="logs", log_level=logging.INFO):
        """Configure logging and return the log file path."""
        os.makedirs(log_dir, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        log_file = os.path.join(log_dir, f"training_{timestamp}.log")

        logging.basicConfig(
            level=log_level,
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            handlers=[
                logging.FileHandler(log_file, encoding='utf-8'),
                logging.StreamHandler()
            ]
        )

        trainer_logger = logging.getLogger('trainer')
        trainer_logger.setLevel(log_level)

        eval_logger = logging.getLogger('evaluation')
        eval_logger.setLevel(log_level)

        return log_file

    @classmethod
    def get_trainer_logger(cls):
        """Return the trainer logger."""
        return logging.getLogger('trainer')

    @classmethod
    def get_eval_logger(cls):
        """Return the evaluation logger."""
        return logging.getLogger('evaluation')

    @classmethod
    def get_entity_type(cls, entity_id: int) -> str:
        """Infer entity type from entity id range."""
        if 0 <= entity_id <= 866:
            return "disease"
        elif 867 <= entity_id <= 1368:
            return "herb"
        elif 1369 <= entity_id <= 15097:
            return "molecule"
        elif 15098 <= entity_id <= 18437:
            return "target"
        else:
            return "unknown"

    @classmethod
    def get_entity_type_id(cls, entity_type: str) -> int:
        """Map entity type string to integer id."""
        for type_id, type_name in cls.ENTITY_TYPES.items():
            if type_name == entity_type:
                return type_id
        return 0

    # Device selection
    GPU_CONFIG = {
        "train_device": "cuda:0",
        "inference_device": "cuda:0",
        "data_parallel": False,
    }

    @classmethod
    def get_device(cls, mode="train"):
        """Return torch.device for a given mode (train/inference)."""
        device_str = cls.GPU_CONFIG.get(f"{mode}_device", "cuda:0")
        if device_str.startswith("cuda") and not torch.cuda.is_available():
            print("CUDA is not available; falling back to CPU")
            return torch.device("cpu")
        return torch.device(device_str)


    @classmethod
    def setup_cuda(cls):
        """Best-effort CUDA setup and device info logging."""
        if torch.cuda.is_available():
            try:
                device = cls.get_device()
                torch.cuda.set_device(device)
                device_id = torch.cuda.current_device()
                print(f"Using GPU: {torch.cuda.get_device_name(device_id)}")
                print(f"GPU memory: {torch.cuda.get_device_properties(device_id).total_memory / 1024 ** 3:.1f} GB")
            except Exception as e:
                print(f"Failed to set CUDA device: {e}")
                print("Falling back to default device")
                torch.cuda.set_device(0)
        else:
            print("Using CPU")
